spring:
  application:
    name: currency-conversion

  devtools:
    livereload:
      port: 36611

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8100

---
spring:
  config:
    activate:
      on-profile: port8101

  devtools:
    livereload:
      port: 36612

server:
  port: 8101

---
spring:
  config:
    activate:
      on-profile: port8102

  devtools:
    livereload:
      port: 36613

server:
  port: 8102
